export const searchItems = [
  { title: 'Smartphone', category: 'Electronics' },
  { title: 'Laptop', category: 'Electronics' },
  { title: 'Wireless Earbuds', category: 'Electronics' },
  { title: 'Smartwatch', category: 'Electronics' },
  { title: 'Bluetooth Speaker', category: 'Electronics' },
  { title: 'Running Shoes', category: 'Footwear' },
  { title: 'Sneakers', category: 'Footwear' },
  { title: 'Leather Boots', category: 'Footwear' },
  { title: 'Jeans', category: 'Clothing' },
  { title: 'T-Shirt', category: 'Clothing' },
  { title: 'Hoodie', category: 'Clothing' },
  { title: 'Jacket', category: 'Clothing' },
  { title: 'Backpack', category: 'Accessories' },
  { title: 'Sunglasses', category: 'Accessories' },
  { title: 'Wristwatch', category: 'Accessories' },
  { title: 'Coffee Maker', category: 'Home Appliances' },
  { title: 'Blender', category: 'Home Appliances' },
  { title: 'Vacuum Cleaner', category: 'Home Appliances' },
  { title: 'Office Chair', category: 'Furniture' },
  { title: 'Dining Table', category: 'Furniture' },
  { title: 'LED Monitor', category: 'Electronics' },
  { title: 'Gaming Console', category: 'Electronics' },
];
