import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
  card: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-start',     // Align content to the top
    borderRadius: 15,
    position: 'relative',
    width: 320,
    minHeight: 420,
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    margin: 'auto',
  },
  media: {
    height: 250,
    width: '100%',
    objectFit: 'cover',
    backgroundColor: '#f0f0f0',
    display: 'block',
  },
  overlay: {
    position: 'absolute',
    top: 10,
    left: 10,
    color: 'white',
    padding: '6px 10px',
    borderRadius: 5,
  },
  overlay2: {
    position: 'absolute',
    top: 10,
    right: 10,
    color: 'white',
    padding: '6px 10px',
    borderRadius: 5,
  },
  details: {
    display: 'flex',
    justifyContent: 'space-between',
    margin: '10px 16px 0 16px',
    flexWrap: 'wrap',
  },
  title: {
    margin: '10px 16px 0 16px',
    fontWeight: 600,
    fontSize: '1.5rem',
    fontFamily: 'Arial, sans-serif',
    color: '#333',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  message: {
    margin: '10px 16px',
    fontSize: '0.95rem',
    color: '#444',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    minHeight: '3.6em',
  },
  cardActions: {
    padding: '0 16px 8px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
    flexDirection: 'column',
  },
}));
  