export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const SIGNUP = 'SIGNUP';

export const FETCH_UNVERIFIED_CATEGORIES = 'FETCH_UNVERIFIED_CATEGORIES';
export const APPROVE_CATEGORY_SUCCESS = 'APPROVE_CATEGORY_SUCCESS';
export const APPROVE_CATEGORY_FAIL = 'APPROVE_CATEGORY_FAIL';
export const REJECT_CATEGORY_SUCCESS = 'REJECT_CATEGORY_SUCCESS';
export const REJECT_CATEGORY_FAIL = 'REJECT_CATEGORY_FAIL';

export const FETCH_UNVERIFIED_STAFF = 'FETCH_UNVERIFIED_STAFF';
export const APPROVE_STAFF_SUCCESS = 'APPROVE_STAFF_SUCCESS';
export const APPROVE_STAFF_FAIL = 'APPROVE_STAFF_FAIL';
export const REJECT_STAFF_SUCCESS = 'REJECT_STAFF_SUCCESS';
export const REJECT_STAFF_FAIL = 'REJECT_STAFF_FAIL';